resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=487abbb90747060002030bfcd05ffd0f39f3c272

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=487abbb90747060002030bfcd05ffd0f39f3c272

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=487abbb90747060002030bfcd05ffd0f39f3c272

images:
  - name: ghcr.io/smoell/sdlc-gitops-sample-stack/pass-api
    newTag: "487abbb90747060002030bfcd05ffd0f39f3c272"

  - name: ghcr.io/smoell/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "487abbb90747060002030bfcd05ffd0f39f3c272"

  - name: ghcr.io/smoell/sdlc-gitops-sample-stack/pass-image-api
    newTag: "487abbb90747060002030bfcd05ffd0f39f3c272"
